CREATE TABLE Sensors(
    SID SERIAL PRIMARY KEY NOT NULL,
    SensorName VARCHAR(50) NOT NULL
);

CREATE TABLE Attributes(
    AID SERIAL PRIMARY KEY NOT NULL,
    AttrName VARCHAR(30) NOT NULL,
    Units VARCHAR(20) NOT NULL
);

CREATE TABLE Data(
    SID INTEGER REFERENCES Sensos(SID),
    AID INTEGER REFERENCES Attributes(AID),
    Timestamp TIMESTAMP NOT NULL,
    DataVal REAL NOT NULL
);